language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex src/bin/tools/ci-travis.bash
env:
  - OPAM_SWITCH=system
cache:
  directories:
  - $HOME/.opam
